"""
Django settings for processor project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path
import os
import dotenv
import sys
# Load environment variables from .hc_to_app_env file
def get_env_path():
    """Get the absolute path to the environment file."""
    if hasattr(sys, '_MEIPASS'):
        # Running in PyInstaller bundle - use the directory where the .exe is located
        env_path = os.path.abspath(os.path.join(os.path.dirname(sys.executable), "..", "..", ".hc_to_app_env"))
        return env_path
    else:
        # Running in development - use the BASE_DIR approach
        return os.path.abspath(os.path.join(os.path.dirname(__file__), '../../cameravision/resources/.hc_to_app_env'))

ENV_PATH = get_env_path()
if not os.path.exists(ENV_PATH):
    raise FileNotFoundError(f"Environment file not found: {ENV_PATH}")
else:
    print(f"Loading environment variables from: {ENV_PATH}")

dotenv.load_dotenv(ENV_PATH)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u_mwofv@-lzg+exb%ojkn6#(@wsgwh8a6qkefa+2^2^hp*m$4f'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    "0.0.0.0"
    "localhost",
    "127.0.0.1",
    os.getenv("BACKEND_SERVER_DOMAIN", "localhost")
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api',
    'record',
    'cronjob',
    'corsheaders',
    'channels',
    'ai'
]

ASGI_APPLICATION = "processor.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"  # For testing only
        # For production: use Redis backend
    }
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'processor.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'processor.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True
JOB_CHECKER_ENABLED=False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Allow frontend dev server for CORS
CORS_ALLOW_ALL_ORIGINS = False

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    f"http://{os.getenv('BACKEND_SERVER_DOMAIN')}:{os.getenv('BACKEND_SERVER_PORT')}"
]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    f"http://{os.getenv('BACKEND_SERVER_DOMAIN')}:{os.getenv('BACKEND_SERVER_PORT')}"
]



if os.getenv("CACHE_DIR") is None:
    raise EnvironmentError("CACHE_DIR environment variable is not set. Please set it to the desired cache directory.")


def get_cache_directory():
    """Get the appropriate cache directory based on runtime environment."""
    try:
        # For PyInstaller, create cache relative to the executable location
        if hasattr(sys, '_MEIPASS'):
            # Running in PyInstaller bundle - use the directory where the .exe is located
            exe_dir = os.path.dirname(sys.executable)
            return os.path.join(exe_dir, os.environ.get("CACHE_DIR", "cache"))
        else:
            # Running in development - use the BASE_DIR approach
            return os.path.abspath(os.path.join(os.path.dirname(__file__), "..", os.environ.get("CACHE_DIR", "cache")))
    except:
        # Fallback: use current working directory
        return os.path.join(os.getcwd(), os.environ.get("CACHE_DIR", "cache"))

# Get cache directory but don't create it yet (let the application create it when first used)
cache_dir = get_cache_directory()

if not cache_dir:
    raise ValueError("CACHE_DIR environment variable must be set and non-empty.")

MEDIA_URL = f'/{os.path.basename(cache_dir)}/'
MEDIA_ROOT = cache_dir
# Ensure MEDIA_ROOT exists
if not os.path.exists(MEDIA_ROOT):
    os.makedirs(MEDIA_ROOT, exist_ok=True)

def get_log_directory():
    """Get the appropriate log directory based on runtime environment."""
    try:
        # For PyInstaller, create logs relative to the executable location
        if hasattr(sys, '_MEIPASS'):
            # Running in PyInstaller bundle - use the directory where the .exe is located
            exe_dir = os.path.dirname(sys.executable)
            return os.path.join(exe_dir, os.environ.get("LOGGER_DIRECTORY", "logs"))
        else:
            # Running in development - use the BASE_DIR approach
            return os.path.abspath(os.path.join(os.path.dirname(__file__), "..", os.environ.get("LOGGER_DIRECTORY", "logs")))
    except:
        # Fallback: use current working directory
        return os.path.join(os.getcwd(), os.environ.get("LOGGER_DIRECTORY", "logs"))

def get_ffmpeg_path():
    """Get the appropriate FFmpeg path based on runtime environment."""
    try:
        # For PyInstaller, create logs relative to the executable location
        if hasattr(sys, '_MEIPASS'):
            # Running in PyInstaller bundle - use the directory where the .exe is located
            exe_dir = os.path.dirname(sys.executable)
            return os.path.join(exe_dir, "_internal", "backend", os.environ.get("FFMPEG_PATH", "apps/ffmpeg/bin/ffmpeg.exe"))
        else:
            # Running in development - use the BASE_DIR approach
            return os.path.abspath(os.path.join(BASE_DIR, os.environ.get("FFMPEG_PATH", "apps/ffmpeg/bin/ffmpeg.exe")))
    except:
        # Fallback: use current working directory
        return os.path.join(os.getcwd(), os.environ.get("FFMPEG_PATH", "apps/ffmpeg/bin/ffmpeg.exe"))

FFMPEG_PATH = get_ffmpeg_path()
# Get log directory but don't create it yet (let the logger create it when first used)
log_dir = get_log_directory()
if not os.path.exists(log_dir):
    os.makedirs(log_dir, exist_ok=True)
django_log_filename = os.path.join(log_dir, 'django.log')

# Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': django_log_filename,
            'maxBytes': 1024*1024*15,  # 15MB
            'backupCount': 10,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'cameravision': {
            'handlers': ['console', 'file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Import and initialize the global logger
# Global logger instance 
from .logger import Logger

APP_LOGGER = Logger(BASE_DIR)

ASGI_APPLICATION = 'processor.asgi.application'

