# Generated by Django 5.2.4 on 2025-07-24 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('record', '0010_record_finished_detecting'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for the AI model.', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Name of the AI model.', max_length=100)),
                ('version', models.CharField(help_text='Version of the AI model.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of the AI model.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the model was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the model was last updated.')),
            ],
        ),
        migrations.CreateModel(
            name='CarDetectionInstance',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for the car detection model.', primary_key=True, serialize=False)),
                ('time', models.PositiveIntegerField(help_text='The time in seconds into the record when this detection was made.')),
                ('bounding_box', models.JSONField(help_text='Bounding box coordinates for the detected car.')),
                ('confidence_threshold', models.FloatField(default=0.5, help_text='Confidence threshold for car detection.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the model was created.')),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_detections', to='ai.aimodel')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_detections', to='record.record')),
            ],
        ),
        migrations.CreateModel(
            name='DetectionLines',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for the detection lines.', primary_key=True, serialize=False)),
                ('type_of_turn', models.CharField(help_text='Type of turn for which the lines are defined (e.g., left, right).', max_length=50)),
                ('line_coordinates', models.JSONField(help_text='Coordinates of the detection lines.')),
                ('type_of_line', models.CharField(choices=[('entry', 'ENTRY'), ('exit', 'EXIT'), ('middle', 'MIDDLE')], help_text='Type of line (entry, exit, middle).', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the model was created.')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_lines', to='record.record')),
            ],
        ),
        migrations.CreateModel(
            name='TurnDetectionInstance',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for the turn detection model.', primary_key=True, serialize=False)),
                ('time', models.PositiveIntegerField(help_text='The time in seconds into the record when this detection was made.')),
                ('turn_type', models.CharField(help_text='Type of turn detected (e.g., left, right).', max_length=50)),
                ('confidence_threshold', models.FloatField(default=0.5, help_text='Confidence threshold for turn detection.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the model was created.')),
                ('ai_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_detections', to='ai.aimodel')),
                ('car_detection_instance', models.ForeignKey(help_text='Reference to the car detection instance.', on_delete=django.db.models.deletion.CASCADE, related_name='turn_detections', to='ai.cardetectioninstance')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turn_detections', to='record.record')),
            ],
        ),
    ]
