# Generated by Django 5.2.4 on 2025-08-16 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifiedAutoCounter',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for the modified auto counter.', primary_key=True, serialize=False)),
                ('time', models.DateField(auto_now_add=True, help_text='The time in seconds into the record when this count was made.')),
                ('version', models.CharField(default='v1', help_text='Version of the auto counter algorithm.', max_length=10)),
                ('file_name', models.TextField(help_text='File name associated with the count data.')),
                ('divide_time', models.FloatField(default=0.1, help_text='Time interval for dividing counts.')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_auto_counters', to='record.record')),
            ],
        ),
    ]
