# Generated by Django 5.2.4 on 2025-08-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodetection',
            name='version',
            field=models.CharField(default='v1', help_text='Version of the auto counter algorithm.', max_length=10),
        ),
    ]
