# Generated by Django 5.2.4 on 2025-07-24 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionlines',
            name='type_of_line',
        ),
        migrations.RemoveField(
            model_name='detectionlines',
            name='type_of_turn',
        ),
    ]
