# Generated by Django 5.2.4 on 2025-08-18 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_modifiedautocounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='autocounter',
            name='version',
            field=models.CharField(default='v1', help_text='Version of the auto counter algorithm.', max_length=10),
        ),
    ]
