# Generated by Django 5.2.4 on 2025-09-03 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_autodetection_version'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCount',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for the auto count.', primary_key=True, serialize=False)),
                ('time', models.DateField(auto_now_add=True, help_text='The time in seconds into the record when this count was made.')),
                ('file_name', models.TextField(help_text='File name associated with the count data.')),
                ('version', models.CharField(default='v1', help_text='Version of the auto counter algorithm.', max_length=10)),
                ('divide_time', models.FloatField(default=0.1, help_text='Time interval for dividing counts.')),
                ('lines', models.ForeignKey(help_text='Reference to the detection lines used for counting.', on_delete=django.db.models.deletion.CASCADE, related_name='auto_counts', to='ai.detectionlines')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_counts', to='record.record')),
            ],
        ),
    ]
