# Generated by Django 5.2.4 on 2025-07-24 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_remove_detectionlines_type_of_line_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectionlines',
            old_name='line_coordinates',
            new_name='lines',
        ),
    ]
