# Generated by Django 5.2.4 on 2025-09-06 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_autocount'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodetection',
            name='detection_lines',
            field=models.ForeignKey(blank=True, help_text='Reference to the detection lines used for counting.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_detections', to='ai.detectionlines'),
        ),
        migrations.CreateModel(
            name='AutoDetectionCheckpoint',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for the auto detection checkpoint.', primary_key=True, serialize=False)),
                ('created_time', models.DateField(auto_now_add=True, help_text='The created date time')),
                ('version', models.CharField(default='v1', help_text='Version of the auto counter algorithm.', max_length=10)),
                ('divide_time', models.FloatField(default=0.1, help_text='Time interval for dividing counts.')),
                ('last_frame_captured', models.IntegerField(default=0, help_text='The last frame number that was processed.')),
                ('detection_lines', models.ForeignKey(blank=True, help_text='Reference to the detection lines used for counting.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auto_detection_checkpoints', to='ai.detectionlines')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_detection_checkpoints', to='record.record')),
            ],
        ),
    ]
