# Generated by Django 5.2.4 on 2025-07-25 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_rename_line_coordinates_detectionlines_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionlines',
            name='lines',
            field=models.JSONField(default={'left': {'entry': [], 'exit': []}, 'right': {'entry': [], 'exit': []}, 'through': {'entry': [], 'exit': []}}, help_text='Coordinates of the detection lines.'),
        ),
    ]
