# Generated by Django 5.2.4 on 2025-09-07 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_autodetection_detection_lines_and_more'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autodetectioncheckpoint',
            name='total_frames',
            field=models.IntegerField(default=0, help_text='Total number of frames in the video.'),
        ),
        migrations.CreateModel(
            name='DetectionProcess',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for the detection process.', primary_key=True, serialize=False)),
                ('version', models.CharField(default='v1', help_text='Version of the auto counter algorithm.', max_length=10)),
                ('divide_time', models.FloatField(default=0.1, help_text='Time interval for dividing counts.')),
                ('done', models.BooleanField(default=False, help_text='Indicates if the detection process is complete.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the detection process started.')),
                ('terminated', models.BooleanField(default=False, help_text='Indicates if the detection process was terminated.')),
                ('pid', models.CharField(blank=True, help_text='Process ID of the detection process.', max_length=30, null=True)),
                ('autodetection_checkpoint', models.ForeignKey(blank=True, help_text='Reference to the progress checkpoint.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detection_processes', to='ai.autodetectioncheckpoint')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detection_processes', to='record.record')),
            ],
        ),
    ]
