# Generated by Django 5.2.4 on 2025-07-25 00:17

import ai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0004_alter_detectionlines_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionlines',
            name='lines',
            field=models.JSONField(default=ai.models.DetectionLines.default_lines, help_text='Coordinates of the detection lines.'),
        ),
    ]
