# Generated by Django 5.2.4 on 2025-08-12 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_alter_detectionlines_lines'),
        ('record', '0017_alter_record_record_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCounter',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for the auto counter.', primary_key=True, serialize=False)),
                ('time', models.DateField(help_text='The time in seconds into the record when this count was made.')),
                ('file_name', models.TextField(help_text='File name associated with the count data.')),
                ('divide_time', models.FloatField(default=0.1, help_text='Time interval for dividing counts.')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_counters', to='record.record')),
            ],
        ),
    ]
