# Generated by Django 5.2.4 on 2025-09-07 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_autodetectioncheckpoint_total_frames_and_more'),
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detectionprocess',
            name='autodetection_checkpoint',
        ),
        migrations.AddField(
            model_name='detectionprocess',
            name='terminate_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detectionprocess',
            name='terminate_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='detectionprocess',
            name='terminated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detectionprocess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='detectionprocess',
            name='divide_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='detectionprocess',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detectionprocess',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='detectionprocess',
            name='pid',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='detectionprocess',
            name='record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.record'),
        ),
        migrations.AlterField(
            model_name='detectionprocess',
            name='terminated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detectionprocess',
            name='version',
            field=models.CharField(max_length=10),
        ),
    ]
