# Generated by Django 5.2.4 on 2025-09-07 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_remove_detectionprocess_autodetection_checkpoint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detectionprocess',
            name='id',
            field=models.BigAutoField(help_text='Unique identifier for the detection process.', primary_key=True, serialize=False),
        ),
    ]
