# Generated by Django 5.2.4 on 2025-08-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0006_autocounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocounter',
            name='time',
            field=models.DateField(auto_now_add=True, help_text='The time in seconds into the record when this count was made.'),
        ),
    ]
