# Generated by Django 5.2.4 on 2025-09-07 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0007_alter_detectionprocess_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionprocess',
            name='autodetection_checkpoint',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai.autodetectioncheckpoint'),
        ),
    ]
