# Generated by Django 5.2.4 on 2025-09-15 05:11

import ai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0008_detectionprocess_autodetection_checkpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionlines',
            name='cut_zones',
            field=models.JSONField(default=ai.models.DetectionLines.default_cut_zones, help_text='Polygon coordinates defining the cut zones.'),
        ),
    ]
