# Generated by Django 5.2.4 on 2025-12-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0009_detectionlines_cut_zones'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoiseDetectionProcess',
            fields=[
                ('id', models.BigAutoField(help_text='Unique identifier for the noise detection process.', primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=10)),
                ('pid', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('done', models.BooleanField(default=False)),
                ('terminated', models.BooleanField(default=False)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
