# Generated by Django 5.2.4 on 2025-08-14 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for the Record.', primary_key=True, serialize=False)),
                ('camera_url', models.URLField(help_text='The camera_url of the RTSP stream.')),
                ('start_time', models.DateTimeField(help_text='The time when the Record started.')),
                ('duration', models.PositiveIntegerField(help_text='Duration of the Record in seconds.')),
                ('done', models.BooleanField(default=False, help_text='Indicates if the Record is completed.')),
                ('record_type', models.CharField(choices=[('supervisor', 'SP'), ('costar', 'CS'), ('import', 'IM')], default='supervisor', help_text='Type of the Record, e.g., video, audio, or both.', max_length=50)),
                ('in_process', models.BooleanField(default=False, help_text='Indicates if the Record is currently in process.')),
                ('error', models.TextField(blank=True, help_text='Error message if the Record failed.', null=True)),
                ('token', models.CharField(blank=True, help_text='A unique token for the Record, used for authentication or identification.', max_length=150, null=True)),
                ('finished_detecting', models.BooleanField(default=False, help_text='Indicates if the detecting process for this Record has finished.')),
                ('assigned_to', models.CharField(blank=True, help_text='The user or system assigned to handle this Record.', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FFMPEGLog',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for the FFMPEGLog.', primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('transcode_started_at', 'Transcode Started'), ('transcode_finished_at', 'Transcode Finished'), ('record_started_at', 'Record Started'), ('record_finished_at', 'Record Finished')], help_text='Type of the log entry.', max_length=50)),
                ('log_time', models.DateTimeField(auto_now_add=True, help_text='The time when the log entry was created.')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ffmpeg_logs', to='record.record')),
            ],
        ),
        migrations.CreateModel(
            name='RecordLog',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for the RecordLog.', primary_key=True, serialize=False)),
                ('time', models.PositiveIntegerField(help_text='The time in seconds into the record when this log entry was created.')),
                ('turn_movement', models.CharField(help_text='The key of the input that triggered this log entry.', max_length=100)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='record.record')),
            ],
        ),
        migrations.CreateModel(
            name='RecordNote',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for the RecordNotes.', primary_key=True, serialize=False)),
                ('note', models.TextField(help_text='The note text associated with the Record.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time when the note was created.')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='record.record')),
            ],
        ),
    ]
