# Generated by Django 5.2.3 on 2025-06-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_url', models.URLField(help_text='The camera_url of the RTSP stream.')),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='The time when the Record started.')),
                ('duration', models.PositiveIntegerField(help_text='Duration of the Record in seconds.')),
                ('done', models.BooleanField(default=False, help_text='Indicates if the Record is completed.')),
                ('in_process', models.BooleanField(default=False, help_text='Indicates if the Record is currently in process.')),
                ('error', models.TextField(blank=True, help_text='Error message if the Record failed.', null=True)),
                ('assigned_to', models.CharField(blank=True, help_text='The user or system assigned to handle this Record.', max_length=100, null=True)),
            ],
        ),
    ]
