# Generated by Django 5.2.4 on 2025-10-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='direction',
            field=models.CharField(blank=True, choices=[('eastbount', 'eb'), ('westbound', 'wb'), ('northbound', 'nb'), ('southbound', 'sb')], help_text='The direction of the record, e.g., eastbound, westbound, northbound, southbound.', max_length=50, null=True),
        ),
    ]
