# Generated by Django 5.2.3 on 2025-07-01 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='token',
            field=models.CharField(blank=True, help_text='A unique token for the Record, used for authentication or identification.', max_length=100, null=True),
        ),
    ]
