# Generated by Django 5.2.3 on 2025-07-01 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_record_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='token',
            field=models.CharField(blank=True, help_text='A unique token for the Record, used for authentication or identification.', max_length=150, null=True),
        ),
    ]
