# Generated by Django 5.2.4 on 2025-10-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_record_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='direction',
            field=models.CharField(blank=True, choices=[('eastbount', 'eb'), ('westbound', 'wb'), ('northbound', 'nb'), ('southbound', 'sb'), ('east', 'eb'), ('west', 'wb'), ('north', 'nb'), ('south', 'sb'), ('e', 'eb'), ('w', 'wb'), ('n', 'nb'), ('s', 'sb')], help_text='The direction of the record, e.g., eastbound, westbound, northbound, southbound.', max_length=50, null=True),
        ),
    ]
