# Generated by Django 5.2.4 on 2025-10-07 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_alter_record_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='camera_id',
            field=models.CharField(blank=True, default='0', help_text='The id of the camera inside the RTSP stream.', max_length=50, null=True),
        ),
    ]
