# Generated by Django 5.2.3 on 2025-07-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_alter_record_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='id',
            field=models.AutoField(help_text='Unique identifier for the Record.', primary_key=True, serialize=False),
        ),
    ]
