# Generated by Django 5.2.4 on 2025-12-30 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_record_camera_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='camera_id',
            field=models.CharField(blank=True, default='NA', help_text='The id of the camera inside the RTSP stream.', max_length=50, null=True),
        ),
    ]
