# Generated by Django 5.2.3 on 2025-07-04 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_alter_record_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordLog',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for the RecordLog.', primary_key=True, serialize=False)),
                ('time', models.PositiveIntegerField(help_text='The time in seconds into the record when this log entry was created.')),
                ('turn_movement', models.CharField(help_text='The key of the input that triggered this log entry.', max_length=100)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='record.record')),
            ],
        ),
    ]
