# Generated by Django 5.2.3 on 2025-07-08 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0006_recordlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='record_type',
            field=models.CharField(choices=[('supervisor', 'SP'), ('costar', 'CS')], default='supervisor', help_text='Type of the Record, e.g., video, audio, or both.', max_length=50),
        ),
    ]
