# Generated by Django 5.2.4 on 2025-07-22 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0007_record_record_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordNotes',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for the RecordNotes.', primary_key=True, serialize=False)),
                ('note', models.TextField(help_text='The note text associated with the Record.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time when the note was created.')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='record.record')),
            ],
        ),
    ]
