# Generated by Django 5.2.4 on 2025-07-22 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0008_recordnotes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecordNotes',
            new_name='RecordNote',
        ),
    ]
