# Generated by Django 5.2.4 on 2025-07-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0009_rename_recordnotes_recordnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='finished_detecting',
            field=models.BooleanField(default=False, help_text='Indicates if the detecting process for this Record has finished.'),
        ),
    ]
