# Generated by Django 5.2.4 on 2025-07-28 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0010_record_finished_counting'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='record_finished_at',
            field=models.DateTimeField(blank=True, default=None, help_text='The time when the recording finished, can be different from done time.', null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='record_started_at',
            field=models.DateTimeField(blank=True, default=None, help_text='The time when the recording actually started, can be different from start_time.', null=True),
        ),
    ]
