# Generated by Django 5.2.4 on 2025-07-28 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0011_record_record_finished_at_record_record_started_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_finished_at',
            field=models.DateTimeField(default=None, help_text='The time when the recording finished, can be different from done time.'),
        ),
        migrations.AlterField(
            model_name='record',
            name='record_started_at',
            field=models.DateTimeField(default=None, help_text='The time when the recording actually started, can be different from start_time.'),
        ),
    ]
