# Generated by Django 5.2.4 on 2025-07-28 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0015_alter_record_record_finished_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='record_finished_at',
        ),
        migrations.RemoveField(
            model_name='record',
            name='record_started_at',
        ),
        migrations.CreateModel(
            name='FFMPEGLog',
            fields=[
                ('id', models.AutoField(help_text='Unique identifier for the FFMPEGLog.', primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('transcode_started_at', 'Transcode Started'), ('transcode_finished_at', 'Transcode Finished'), ('record_started_at', 'Record Started'), ('record_finished_at', 'Record Finished')], help_text='Type of the log entry.', max_length=50)),
                ('log_time', models.DateTimeField(auto_now_add=True, help_text='The time when the log entry was created.')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ffmpeg_logs', to='record.record')),
            ],
        ),
    ]
