# Generated by Django 5.2.4 on 2025-08-08 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0016_remove_record_record_finished_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='record_type',
            field=models.CharField(choices=[('supervisor', 'SP'), ('costar', 'CS'), ('import', 'IM')], default='supervisor', help_text='Type of the Record, e.g., video, audio, or both.', max_length=50),
        ),
    ]
